# 4.1数据数组

## 4.1.1 用列表形成数组 

In [4]:
m = [1,2,3,4,5]
n = [m,m,m,m]
n

[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]

In [6]:
#deepcopy函数，用物理副本代替引用指针
from copy import deepcopy
m = [1,2,3,4,5]
n = [m,m,m,m]
n_ = 3 * [deepcopy(m),]
m[0]='python'
print(m,n,n_)#改变原列表后，使用deepcopy的并没有受到影响

['python', 2, 3, 4, 5] [['python', 2, 3, 4, 5], ['python', 2, 3, 4, 5], ['python', 2, 3, 4, 5], ['python', 2, 3, 4, 5]] [[1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]


## 4.1.2 array类

In [2]:
import array
a = array.array('f',[1,2,3,4])#‘f’定义类型

 TIPs:
 1. 可用append&extend，但添加的数据类型要相符，否则报错
 2. 某数与array相乘只是重复元素，与数学理论不符合

In [5]:
#存储array数据,储存到同一目录下
with open('array.apy','wb') as f:
    a.tofile(f)

In [6]:
#读取array
b = array.array('f')#确定b的格式为浮点
with open('array.apy','rb') as f:
    b.fromfile(f,2)
b

array('f', [1.0, 2.0])

In [9]:
#读取array
b = array.array('d')#确定b的格式为double
with open('array.apy','rb') as f:
    b.fromfile(f,2)
b#array中没有double类型，无法读出正确的值

array('d', [2.000000473111868, 512.0001225471497])

# 4.2 常规NumPy数组 

## 4.2.1 基础知识

1. np.arange()\
`a = np.arange(star,end,step,dtype)#end不包括
a = np.arange(end, dtype)#end不包括，0到end之间的整数切片左闭右开，0为第一个`
2. a.sum()
3. a.std()
4. a.cumsum()<span style="border-bottom:3px dashed #DE7171;">元素的累计总和</span>
5. **ndarray可正常进行向量化数学运算**
6. np.exp(a)<span style="border-bottom:3px dashed #DE7171;">计算每个元素的指数值</span>
7. np.sqrt(a)
8. 用math模块计算更快\
`import math
math.sqrt(a)`


In [18]:
import numpy as np
a1 = np.arange(1,5,0.5,dtype=np.float)
a1

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [21]:
a2 = np.arange(5.9,dtype=np.float)
a2

array([0., 1., 2., 3., 4., 5.])

In [20]:
a2[:2]

array([0., 1.])

## 4.2.2多维数组 

1. np.zeros((m,n),dtype,order) <span style="border-bottom:3px dashed #DE7171;">用零填充</span>
2. np.ones <span style="border-bottom:3px dashed #DE7171;">用1填充</span>
3. np.ones_like(c,dtype,order)<span style="border-bottom:3px dashed #DE7171;">用1填充,形状和c相似</span>
4. np.empty((m,n))<span style="border-bottom:3px dashed #DE7171;">不填充</span>
5. np.empty_like(c,dtype,order)<span style="border-bottom:3px dashed #DE7171;">不填充,形状和c相似</span>
6. np.eyes(n) <span style="border-bottom:3px dashed #DE7171;">单位矩阵</span>
7. np.linspace(star,end,num)<span style="border-bottom:3px dashed #DE7171;">一维ndarray对象，数之间均匀间隔，star/end都包括</span>
order有C和F,C行优先，F列优先

## 4.2.3 元信息

1. a.size **元素数量**
2. a.itemsize **一个元素的字节数**
3. a.ndim  **维数**
4. a.shape **ndrray对象组成**
5. a.dtype **元素的类型**
6. a.nbytes **字节总数**

## 4.2.4改变组成大小 

g.reshape() **不改变元素数量，改变形状** \
g.T **转置** \
g.transpose() **转置** \
np.resize(g,(m,n)) **可扩大或者缩小原数组** \
np.hstack((g, 2 * g)) **水平连接** \
np.vstack((g, 2 * g)) **垂直连接** \
g.flatten() **把多维数组扁平化变成一维数组** 


In [29]:
import numpy as np
h = np.random.rand(2,3)
h

array([[0.1965806 , 0.85199299, 0.08272373],
       [0.65831339, 0.3038445 , 0.46890122]])

In [30]:
np.hstack((h,2 * h))

array([[0.1965806 , 0.85199299, 0.08272373, 0.3931612 , 1.70398598,
        0.16544745],
       [0.65831339, 0.3038445 , 0.46890122, 1.31662678, 0.60768901,
        0.93780245]])

In [31]:
np.vstack((h,2 * h))

array([[0.1965806 , 0.85199299, 0.08272373],
       [0.65831339, 0.3038445 , 0.46890122],
       [0.3931612 , 1.70398598, 0.16544745],
       [1.31662678, 0.60768901, 0.93780245]])

In [33]:
h.flatten()#默认扁平化顺序为C（行优先）

array([0.1965806 , 0.85199299, 0.08272373, 0.65831339, 0.3038445 ,
       0.46890122])

In [35]:
h.flatten(order='C')

array([0.1965806 , 0.85199299, 0.08272373, 0.65831339, 0.3038445 ,
       0.46890122])

In [36]:
h.flatten(order='F')

array([0.1965806 , 0.65831339, 0.85199299, 0.3038445 , 0.08272373,
       0.46890122])

In [38]:
for i in h.flat:#C顺序
    print(i,end=',')

0.19658060227531227,0.8519929876772002,0.08272372704088649,0.6583133888616981,0.3038445041850725,0.46890122391679445,

In [39]:
for i in h.ravel(order='C'):#C顺序
    print(i,end=',')

0.19658060227531227,0.8519929876772002,0.08272372704088649,0.6583133888616981,0.3038445041850725,0.46890122391679445,

In [40]:
for i in h.ravel(order='F'):#F顺序
    print(i,end=',')

0.19658060227531227,0.6583133888616981,0.8519929876772002,0.3038445041850725,0.08272372704088649,0.46890122391679445,